version: '3.8'

services:
  emby-controller:
    image: ranjie/emby-controller:latest
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./runtime/log:/app/runtime/log
    ports:
      - "8018:8018"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
