[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/app/runtime/log/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
pidfile=/var/run/supervisord.pid
user=root
loglevel=info

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:queue-worker]
command=php /app/think queue:work --queue main --tries 3 --sleep 3
directory=/app
autostart=true
autorestart=true
startretries=3
startsecs=3
user=www-data
stdout_logfile=/app/runtime/log/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/app/runtime/log/queue-worker-error.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
redirect_stderr=false
